version: "3.8"
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'booqueen'
    restart: always
    ports:
      - "3307:3306"
  booapi:
    build: ./booapi
    environment:
      MYSQL_DATABASE: 'booqueen'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_HOST: db
      DB_DRIVER: mysql
      MYSQL_PORT: db.port
    ports:
      - "5005:5005"
    depends_on:
      - db
    restart: on-failure
